### PR TITLE
Add fix for amd thermal

### LINKED ISSUE #250: Temperatures on some cores do not update
**Describe the bug**
Some temperatures do not update whatever you do on your computer
The temperature the program gets at startup seems to be correct, but some cpu cores do not update after that

**To Reproduce**
1. Ran command 'acs monitor'
2. Specific condition: was plugged in, although that's because my computer does weird stuff when on battery
3. Run something heavy (I used blender to render on CPU)

**Expected behavior**
Some CPU cores shoots up to 90C, as they should, but some other ones stay and do not get updated

**On Laptop**
Version 0.1.8, Fedora R35

### PR DESCRIPTION
**Pull request by JakeRoggenbuck**
fixes #250

### CODE REVIEW

File: src/cpu.rs [hunk 1]
```diff
@@ -53,14 +53,20 @@ pub enum WritableValue {
...
+        let mut cpu_info_path: String = format!(
             "/sys/class/thermal/{}/{}",
             self.name.replace("cpu", "thermal_zone"),
             sub_path
         );
 
+        // If the thermal path does not exist, use the first thermal path only if it exists
         if !Path::new(&cpu_info_path).exists() {
-            return Ok(-1);
+            let test_path = format!("/sys/class/thermal/thermal_zone0/{}", sub_path);
```
Comment (Shuzhengz) [inline src/cpu.rs:64]: hmm idk if test path is the best name, i mean it's supposed to be the temp for the first core

Comment (JakeRoggenbuck) [reply src/cpu.rs]: good point, I'll fix

**Review by Shuzhengz — APPROVED** [review]
